### ISSUE TITLE
Using a cronjob to create/update clustersecret of type kubernetes.io/dockerconfigjson 

### ISSUE THREAD

**Issue by cacaocal** [zakkg3/ClusterSecret#107]
How to create clustersecret using kubectl。
When I execute 
                kubectl create secret docker-registry $DOCKER_SECRET_NAME \
                --docker-server=${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com \
                --docker-username=AWS \
                --docker-password="${ECR_TOKEN}" \
                --namespace=$NAMESPACE_NAME
and yaml don't incloud --docker-username --docker-server this

**Comment by axel7083** [comment]
Sorry for the late answer -

If I am getting this right, you want to create a cluster secret based using a cronjob of type `docker-registry`.

> I am guessing here that the `ECR_TOKEN` is a **temporary** token, and your cronjob is here to renew it, therefore requiring to update the cluster secret.

You cannot directly create the cluster secret, since when you are using the `docker-registry` arguments, kubectl is using an internal generator to generate a `.dockerconfigjson` config. 

Here is some step you can follow

First using the kubectl internal generator to generate the secret on the client side
```
kubectl create secret docker-registry NAME --docker-username=user --docker-password=password --docker-email=email --docker-server=server  --dry-run=client -o json
``` 

The command above will produce the following Secret resource.

```json
{
    "kind": "Secret",
    "apiVersion": "v1",
    "metadata": {
        "name": "example",
        "creationTimestamp": null
    },
    "data": {
        ".dockerconfigjson": "eyJhdXRocyI6eyJzZXJ2ZXIiOnsidXNlcm5hbWUiOiJ1c2VyIiwicGFzc3dvcmQiOiJwYXNzd29yZCIsImVtYWlsIjoiZW1haWwiLCJhdXRoIjoiZFhObGNqcHdZWE56ZDI5eVpBPT0ifX19"
    },
    "type": "kubernetes.io/dockerconfigjson"
}
```

From their, and using your favorite method, you can extract the `data/.dockerconfigjson` token (base64) containing all the information you provided with the arguments you used (--docker-server etc.).

From their you can create a cluster secret   

```yaml
apiVersion: clustersecret.io/v1
kind: ClusterSecret
metadata:
  name: global-secret
  namespace: my-fav-namespce
data:
  .dockerconfigjson: "eyJhdXRocyI6eyJzZXJ2ZXIiOnsidXNlcm5hbWUiOiJ1c2VyIiwicGFzc3dvcmQiOiJwYXNzd29yZCIsImVtYWlsIjoiZW1haWwiLCJhdXRoIjoiZFhObGNqcHdZWE56ZDI5eVpBPT0ifX19"
type: kubernetes.io/dockerconfigjson
```
