### ISSUE TITLE
Wildcard matching?

### ISSUE THREAD

**Issue by IngwiePhoenix** [zakkg3/ClusterSecret#134]
Hello!

I just installed the Postgres Operator and it creates secrets with a particular schema - and I would like to copy the respective secrets across as needed.

Is there a way to wildcard match against the pattern - or do you perhaps know a better method?

Thanks and kind regards,
Ingwie

**Comment by zakkg3** [comment]
Yes, you can use regex, there are examples on the documentation
https://clustersecret.io

**Comment by IngwiePhoenix** [comment]
I found that I can use regexp on `targetNamespace` - but this seems to not be supported:

```yaml
Kind: ClusterSecret
apiVersion: clustersecret.io/v1
metadata:
  namespace: clustersecret
  name: default-wildcard-certifiate
matchNamespace:
  # Any and all namespaces
  - *
avoidNamespaces:
  - default
  - kube-system
data:
  valueFrom:
    secretKeyRef:
      # Match the automatically generated credentials from the Zalando Postgres Cluster Operator
      name: *.default-cluster.credentials.postgresql.acid.zalan.do
      namespace: postgres # this is where the cluster and source secrets are
```

At least, it is not explained or mentioned in any docs on the website unfortunately.
ref https://clustersecret.io/valuefromsecret/
