### ISSUE TITLE
feature request: Sync secret to target ns

### ISSUE THREAD

**Issue by mihaigalos** [zakkg3/ClusterSecret#148]
I would like to use the operator to simply sync an already existing secret from ns A to B.
```yaml
kind: ClusterSecret
apiVersion: clustersecret.io/v1
metadata:
  namespace: ns-A
  name: default-wildcard-certifiate
matchNamespace:
  - ns-B
avoidNamespaces:
  - supersecret-ns
#  data: # Commented-out means transparent sync of all fields
#    tls.crt: BASE64
#    tls.key: BASE64
```
Let me know what you think here, I might dig deeper in the code if you think it's doable.
