### ISSUE TITLE
Secrets not updating when modified secrets are deployed

### ISSUE THREAD

**Issue by acidbotmaker** [zakkg3/ClusterSecret#41]
I'm using the following code to set secret in **demo** namespace:
```
apiVersion: clustersecret.io/v1
kind: ClusterSecret
metadata:
  name: secret-identity
matchNamespace:
  - demo
data:
  MESSAGE: SSdtIEJhdG1hbg==
```

But when I modify the MESSAGE value and redeploy using `kubectl apply -f demo-secret.yml` secrets are not updated. I need to delete the secret and redeploy them for changes to take affect.
