### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by are3k** [zakkg3/ClusterSecret#51]
Minikube v1.27.0 running Kubernetes v1.25.0 on containerd 1.6.8

Installing with `kubectl apply -f ./yaml` returned this:

```shell
namespace/clustersecret created
serviceaccount/clustersecret-account created
clusterrole.rbac.authorization.k8s.io/clustersecret-role-cluster created
role.rbac.authorization.k8s.io/clustersecret-role-namespaced created
clusterrolebinding.rbac.authorization.k8s.io/clustersecret-rolebinding-cluster created
rolebinding.rbac.authorization.k8s.io/clustersecret-rolebinding-namespaced created
customresourcedefinition.apiextensions.k8s.io/clustersecrets.clustersecret.io created
Error from server (BadRequest): error when creating "yaml/02_deployment.yaml": Deployment in version "v1" cannot be handled as a Deployment: strict decoding error: unknown field "spec.matchLabels"
```

This error persisted until I ran this version of the deployment manifest, with the offending "spec.matchLabels" removed:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clustersecret
  namespace: clustersecret
  labels:
    app: clustersecret
spec:
    selector:
      matchLabels:
        app: clustersecret
    template:
      metadata:
        labels:
          app: clustersecret
      spec:
        serviceAccountName: clustersecret-account
        # imagePullSecrets:
        # - name: regcred
        containers:
        - name: clustersecret
          image: flag5/clustersecret:0.0.8-beta
          # imagePullPolicy: Always
          # Uncomment next lines for debug:
          # command:
          #   - "kopf"
          #   - "run"
          #   - "-A"
          #   - "/src/handlers.py"
          #   - "--verbose"
```

The operator works after this, and new ClusterSecrets are cloned. I wonder if it's a bug, or am I missing something?

**Comment by Larswa** [comment]
No you did it right.  There is a matchLabels too much in there. 

``` yaml
spec:
    matchLabels:  <-- should be removed
    selector:
      matchLabels:
        app: clustersecret
```
